export const BLOCKS = {
  AIR: {
    id: 0,
    name: "Air",
    texture: null,
    isTransparent: true,
    isFluid: false,
    geometry: "cube",
  },
  STONE: {
    id: 1,
    name: "Stone",
    texture: "stone.png",
    isTransparent: false,
    geometry: "cube",
  },
  GRANITE: {
    id: 2,
    name: "Granite",
    texture: "granite.png",
    isTransparent: false,
    geometry: "cube",
  },
  POLISHED_GRANITE: {
    id: 3,
    name: "Polished Granite",
    texture: "polished_granite.png",
    isTransparent: false,
    geometry: "cube",
  },
  DIORITE: {
    id: 4,
    name: "Diorite",
    texture: "diorite.png",
    isTransparent: false,
    geometry: "cube",
  },
  POLISHED_DIORITE: {
    id: 5,
    name: "Polished Diorite",
    texture: "polished_diorite.png",
    isTransparent: false,
    geometry: "cube",
  },
  ANDESITE: {
    id: 6,
    name: "Andesite",
    texture: "andesite.png",
    isTransparent: false,
    geometry: "cube",
  },
  POLISHED_ANDESITE: {
    id: 7,
    name: "Polished Andesite",
    texture: "polished_andesite.png",
    isTransparent: false,
    geometry: "cube",
  },
  GRASS_BLOCK: {
    id: 8,
    name: "Grass Block",
    texture: {
      top: "grass_block_top.png",
      bottom: "dirt.png",
      side: "grass_block_side.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  DIRT: {
    id: 9,
    name: "Dirt",
    texture: "dirt.png",
    isTransparent: false,
    geometry: "cube",
  },
  COARSE_DIRT: {
    id: 10,
    name: "Coarse Dirt",
    texture: "coarse_dirt.png",
    isTransparent: false,
    geometry: "cube",
  },
  PODZOL: {
    id: 11,
    name: "Podzol",
    texture: {
      top: "podzol_top.png",
      bottom: "dirt.png",
      side: "podzol_side.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  COBBLESTONE: {
    id: 12,
    name: "Cobblestone",
    texture: "cobblestone.png",
    isTransparent: false,
    geometry: "cube",
  },
  OAK_PLANKS: {
    id: 13,
    name: "Oak Planks",
    texture: "oak_planks.png",
    isTransparent: false,
    geometry: "cube",
  },
  SPRUCE_PLANKS: {
    id: 14,
    name: "Spruce Planks",
    texture: "spruce_planks.png",
    isTransparent: false,
    geometry: "cube",
  },
  BIRCH_PLANKS: {
    id: 15,
    name: "Birch Planks",
    texture: "birch_planks.png",
    isTransparent: false,
    geometry: "cube",
  },
  JUNGLE_PLANKS: {
    id: 16,
    name: "Jungle Planks",
    texture: "jungle_planks.png",
    isTransparent: false,
    geometry: "cube",
  },
  ACACIA_PLANKS: {
    id: 17,
    name: "Acacia Planks",
    texture: "acacia_planks.png",
    isTransparent: false,
    geometry: "cube",
  },
  DARK_OAK_PLANKS: {
    id: 18,
    name: "Dark Oak Planks",
    texture: "dark_oak_planks.png",
    isTransparent: false,
    geometry: "cube",
  },
  BEDROCK: {
    id: 19,
    name: "Bedrock",
    texture: "bedrock.png",
    isTransparent: false,
    geometry: "cube",
  },
  SAND: {
    id: 20,
    name: "Sand",
    texture: "sand.png",
    isTransparent: false,
    geometry: "cube",
  },
  RED_SAND: {
    id: 21,
    name: "Red Sand",
    texture: "red_sand.png",
    isTransparent: false,
    geometry: "cube",
  },
  GRAVEL: {
    id: 22,
    name: "Gravel",
    texture: "gravel.png",
    isTransparent: false,
    geometry: "cube",
  },
  GOLD_ORE: {
    id: 23,
    name: "Gold Ore",
    texture: "gold_ore.png",
    isTransparent: false,
    geometry: "cube",
  },
  IRON_ORE: {
    id: 24,
    name: "Iron Ore",
    texture: "iron_ore.png",
    isTransparent: false,
    geometry: "cube",
  },
  COAL_ORE: {
    id: 25,
    name: "Coal Ore",
    texture: "coal_ore.png",
    isTransparent: false,
    geometry: "cube",
  },
  OAK_LOG: {
    id: 26,
    name: "Oak Log",
    texture: {
      top: "oak_log_top.png",
      bottom: "oak_log_top.png",
      side: "oak_log.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  SPRUCE_LOG: {
    id: 27,
    name: "Spruce Log",
    texture: {
      top: "spruce_log_top.png",
      bottom: "spruce_log_top.png",
      side: "spruce_log.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  BIRCH_LOG: {
    id: 28,
    name: "Birch Log",
    texture: {
      top: "birch_log_top.png",
      bottom: "birch_log_top.png",
      side: "birch_log.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  JUNGLE_LOG: {
    id: 29,
    name: "Jungle Log",
    texture: {
      top: "jungle_log_top.png",
      bottom: "jungle_log_top.png",
      side: "jungle_log.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  ACACIA_LOG: {
    id: 30,
    name: "Acacia Log",
    texture: {
      top: "acacia_log_top.png",
      bottom: "acacia_log_top.png",
      side: "acacia_log.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  DARK_OAK_LOG: {
    id: 31,
    name: "Dark Oak Log",
    texture: {
      top: "dark_oak_log_top.png",
      bottom: "dark_oak_log_top.png",
      side: "dark_oak_log.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  STRIPPED_OAK_LOG: {
    id: 32,
    name: "Stripped Oak Log",
    texture: {
      top: "stripped_oak_log_top.png",
      bottom: "stripped_oak_log_top.png",
      side: "stripped_oak_log.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  OAK_LEAVES: {
    id: 33,
    name: "Oak Leaves",
    texture: "oak_leaves.png",
    isTransparent: true,
    geometry: "cube",
  },
  SPRUCE_LEAVES: {
    id: 34,
    name: "Spruce Leaves",
    texture: "spruce_leaves.png",
    isTransparent: true,
    geometry: "cube",
  },
  BIRCH_LEAVES: {
    id: 35,
    name: "Birch Leaves",
    texture: "birch_leaves.png",
    isTransparent: true,
    geometry: "cube",
  },
  JUNGLE_LEAVES: {
    id: 36,
    name: "Jungle Leaves",
    texture: "jungle_leaves.png",
    isTransparent: true,
    geometry: "cube",
  },
  ACACIA_LEAVES: {
    id: 37,
    name: "Acacia Leaves",
    texture: "acacia_leaves.png",
    isTransparent: true,
    geometry: "cube",
  },
  DARK_OAK_LEAVES: {
    id: 38,
    name: "Dark Oak Leaves",
    texture: "dark_oak_leaves.png",
    isTransparent: true,
    geometry: "cube",
  },
  SPONGE: {
    id: 39,
    name: "Sponge",
    texture: "sponge.png",
    isTransparent: false,
    geometry: "cube",
  },
  GLASS: {
    id: 40,
    name: "Glass",
    texture: "glass.png",
    isTransparent: true,
    geometry: "cube",
  },
  LAPIS_ORE: {
    id: 41,
    name: "Lapis Ore",
    texture: "lapis_ore.png",
    isTransparent: false,
    geometry: "cube",
  },
  LAPIS_BLOCK: {
    id: 42,
    name: "Lapis Block",
    texture: "lapis_block.png",
    isTransparent: false,
    geometry: "cube",
  },
  DISPENSER: {
    id: 43,
    name: "Dispenser",
    texture: {
      top: "furnace_top.png",
      bottom: "furnace_top.png",
      front: "dispenser_front.png",
      side: "furnace_side.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  SANDSTONE: {
    id: 44,
    name: "Sandstone",
    texture: {
      top: "sandstone_top.png",
      bottom: "sandstone_bottom.png",
      side: "sandstone.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  NOTE_BLOCK: {
    id: 45,
    name: "Note Block",
    texture: "note_block.png",
    isTransparent: false,
    geometry: "cube",
  },
  WHITE_WOOL: {
    id: 46,
    name: "White Wool",
    texture: "white_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  ORANGE_WOOL: {
    id: 47,
    name: "Orange Wool",
    texture: "orange_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  MAGENTA_WOOL: {
    id: 48,
    name: "Magenta Wool",
    texture: "magenta_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  LIGHT_BLUE_WOOL: {
    id: 49,
    name: "Light Blue Wool",
    texture: "light_blue_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  YELLOW_WOOL: {
    id: 50,
    name: "Yellow Wool",
    texture: "yellow_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  LIME_WOOL: {
    id: 51,
    name: "Lime Wool",
    texture: "lime_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  PINK_WOOL: {
    id: 52,
    name: "Pink Wool",
    texture: "pink_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  GRAY_WOOL: {
    id: 53,
    name: "Gray Wool",
    texture: "gray_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  LIGHT_GRAY_WOOL: {
    id: 54,
    name: "Light Gray Wool",
    texture: "light_gray_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  CYAN_WOOL: {
    id: 55,
    name: "Cyan Wool",
    texture: "cyan_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  PURPLE_WOOL: {
    id: 56,
    name: "Purple Wool",
    texture: "purple_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  BLUE_WOOL: {
    id: 57,
    name: "Blue Wool",
    texture: "blue_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  BROWN_WOOL: {
    id: 58,
    name: "Brown Wool",
    texture: "brown_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  GREEN_WOOL: {
    id: 59,
    name: "Green Wool",
    texture: "green_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  RED_WOOL: {
    id: 60,
    name: "Red Wool",
    texture: "red_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  BLACK_WOOL: {
    id: 61,
    name: "Black Wool",
    texture: "black_wool.png",
    isTransparent: false,
    geometry: "cube",
  },
  GOLD_BLOCK: {
    id: 62,
    name: "Gold Block",
    texture: "gold_block.png",
    isTransparent: false,
    geometry: "cube",
  },
  IRON_BLOCK: {
    id: 63,
    name: "Iron Block",
    texture: "iron_block.png",
    isTransparent: false,
    geometry: "cube",
  },
  BRICKS: {
    id: 64,
    name: "Bricks",
    texture: "bricks.png",
    isTransparent: false,
    geometry: "cube",
  },
  TNT: {
    id: 65,
    name: "TNT",
    texture: {
      top: "tnt_top.png",
      bottom: "tnt_bottom.png",
      side: "tnt_side.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  BOOKSHELF: {
    id: 66,
    name: "Bookshelf",
    texture: "bookshelf.png",
    isTransparent: false,
    geometry: "cube",
  },
  MOSSY_COBBLESTONE: {
    id: 67,
    name: "Mossy Cobblestone",
    texture: "mossy_cobblestone.png",
    isTransparent: false,
    geometry: "cube",
  },
  OBSIDIAN: {
    id: 68,
    name: "Obsidian",
    texture: "obsidian.png",
    isTransparent: false,
    geometry: "cube",
  },
  TORCH: {
    id: 69,
    name: "Torch",
    texture: "torch.png",
    isTransparent: true,
    geometry: "cross", // Should be cross or special torch geometry. Using cross for now.
  },
  OAK_STAIRS: {
    id: 70,
    name: "Oak Stairs",
    texture: "oak_planks.png",
    isTransparent: true,
    geometry: "stairs",
  },
  CHEST: {
    id: 71,
    name: "Chest",
    texture: {
      top: "chest_top.png",
      bottom: "chest_bottom.png",
      side: "chest_side.png",
      front: "chest_front.png",
    },
    isTransparent: true,
    geometry: "custom", // 0.875
  },
  DIAMOND_ORE: {
    id: 72,
    name: "Diamond Ore",
    texture: "diamond_ore.png",
    isTransparent: false,
    geometry: "cube",
  },
  DIAMOND_BLOCK: {
    id: 73,
    name: "Diamond Block",
    texture: "diamond_block.png",
    isTransparent: false,
    geometry: "cube",
  },
  CRAFTING_TABLE: {
    id: 74,
    name: "Crafting Table",
    texture: {
      top: "crafting_table_top.png",
      bottom: "oak_planks.png",
      side: "crafting_table_side.png",
      front: "crafting_table_front.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  FURNACE: {
    id: 75,
    name: "Furnace",
    texture: {
      top: "furnace_top.png",
      bottom: "furnace_top.png",
      side: "furnace_side.png",
      front: "furnace_front.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  LADDER: {
    id: 76,
    name: "Ladder",
    texture: "ladder.png",
    isTransparent: true,
    geometry: "ladder",
  },
  RAIL: {
    id: 77,
    name: "Rail",
    texture: "rail.png",
    isTransparent: true,
    geometry: "rail",
  },
  COBBLESTONE_STAIRS: {
    id: 78,
    name: "Cobblestone Stairs",
    texture: "cobblestone.png",
    isTransparent: true,
    geometry: "stairs",
  },
  LEVER: {
    id: 79,
    name: "Lever",
    texture: "lever.png",
    isTransparent: true,
    geometry: "cross", // Placeholder
  },
  STONE_PRESSURE_PLATE: {
    id: 80,
    name: "Stone Pressure Plate",
    texture: "stone.png",
    isTransparent: true,
    geometry: "rail", // Placeholder geometry (flat)
  },
  OAK_PRESSURE_PLATE: {
    id: 81,
    name: "Oak Pressure Plate",
    texture: "oak_planks.png",
    isTransparent: true,
    geometry: "rail", // Placeholder geometry (flat)
  },
  REDSTONE_ORE: {
    id: 82,
    name: "Redstone Ore",
    texture: "redstone_ore.png",
    isTransparent: false,
    geometry: "cube",
  },
  REDSTONE_TORCH: {
    id: 83,
    name: "Redstone Torch",
    texture: "redstone_torch.png",
    isTransparent: true,
    geometry: "cross",
  },
  SNOW: {
    id: 84,
    name: "Snow",
    texture: "snow.png",
    isTransparent: true,
    geometry: "rail", // Flat layer
  },
  ICE: {
    id: 85,
    name: "Ice",
    texture: "ice.png",
    isTransparent: true,
    geometry: "cube",
  },
  SNOW_BLOCK: {
    id: 86,
    name: "Snow Block",
    texture: "snow.png",
    isTransparent: false,
    geometry: "cube",
  },
  CACTUS: {
    id: 87,
    name: "Cactus",
    texture: {
      top: "cactus_top.png",
      bottom: "cactus_bottom.png",
      side: "cactus_side.png",
    },
    isTransparent: true, // Technically smaller than block
    geometry: "custom", // Using cube for now, but maybe shrink?
  },
  CLAY: {
    id: 88,
    name: "Clay",
    texture: "clay.png",
    isTransparent: false,
    geometry: "cube",
  },
  JUKEBOX: {
    id: 89,
    name: "Jukebox",
    texture: {
      top: "jukebox_top.png",
      side: "jukebox_side.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  OAK_FENCE: {
    id: 90,
    name: "Oak Fence",
    texture: "oak_planks.png",
    isTransparent: true,
    geometry: "cube", // Placeholder
  },
  PUMPKIN: {
    id: 91,
    name: "Pumpkin",
    texture: {
      top: "pumpkin_top.png",
      side: "pumpkin_side.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  NETHERRACK: {
    id: 92,
    name: "Netherrack",
    texture: "netherrack.png",
    isTransparent: false,
    geometry: "cube",
  },
  SOUL_SAND: {
    id: 93,
    name: "Soul Sand",
    texture: "soul_sand.png",
    isTransparent: false,
    geometry: "cube",
  },
  GLOWSTONE: {
    id: 94,
    name: "Glowstone",
    texture: "glowstone.png",
    isTransparent: false,
    geometry: "cube",
  },
  JACK_O_LANTERN: {
    id: 95,
    name: "Jack o'Lantern",
    texture: {
      top: "pumpkin_top.png",
      side: "pumpkin_side.png",
      front: "jack_o_lantern.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  CAKE: {
    id: 96,
    name: "Cake",
    texture: {
      top: "cake_top.png",
      bottom: "cake_bottom.png",
      side: "cake_side.png",
    },
    isTransparent: true,
    geometry: "custom", // Should be smaller
  },
  STONE_BRICKS: {
    id: 97,
    name: "Stone Bricks",
    texture: "stone_bricks.png",
    isTransparent: false,
    geometry: "cube",
  },
  MOSSY_STONE_BRICKS: {
    id: 98,
    name: "Mossy Stone Bricks",
    texture: "mossy_stone_bricks.png",
    isTransparent: false,
    geometry: "cube",
  },
  CRACKED_STONE_BRICKS: {
    id: 99,
    name: "Cracked Stone Bricks",
    texture: "cracked_stone_bricks.png",
    isTransparent: false,
    geometry: "cube",
  },
  CHISELED_STONE_BRICKS: {
    id: 100,
    name: "Chiseled Stone Bricks",
    texture: "chiseled_stone_bricks.png",
    isTransparent: false,
    geometry: "cube",
  },
  MELON: {
    id: 101,
    name: "Melon",
    texture: {
      top: "melon_top.png",
      side: "melon_side.png",
    },
    isTransparent: false,
    geometry: "cube",
  },
  OAK_TRAPDOOR: {
    id: 102,
    name: "Oak Trapdoor",
    texture: "oak_trapdoor.png",
    isTransparent: true,
    geometry: "trapdoor",
  },
  SPRUCE_TRAPDOOR: {
    id: 103,
    name: "Spruce Trapdoor",
    texture: "spruce_trapdoor.png",
    isTransparent: true,
    geometry: "trapdoor",
  },
  BIRCH_TRAPDOOR: {
    id: 104,
    name: "Birch Trapdoor",
    texture: "birch_trapdoor.png",
    isTransparent: true,
    geometry: "trapdoor",
  },
  JUNGLE_TRAPDOOR: {
    id: 105,
    name: "Jungle Trapdoor",
    texture: "jungle_trapdoor.png",
    isTransparent: true,
    geometry: "trapdoor",
  },
  ACACIA_TRAPDOOR: {
    id: 106,
    name: "Acacia Trapdoor",
    texture: "acacia_trapdoor.png",
    isTransparent: true,
    geometry: "trapdoor",
  },
  DARK_OAK_TRAPDOOR: {
    id: 107,
    name: "Dark Oak Trapdoor",
    texture: "dark_oak_trapdoor.png",
    isTransparent: true,
    geometry: "trapdoor",
  },
  DANDELION: {
    id: 108,
    name: "Dandelion",
    texture: "dandelion.png",
    isTransparent: true,
    geometry: "cross",
  },
  POPPY: {
    id: 109,
    name: "Poppy",
    texture: "poppy.png",
    isTransparent: true,
    geometry: "cross",
  },
  BLUE_ORCHID: {
    id: 110,
    name: "Blue Orchid",
    texture: "blue_orchid.png",
    isTransparent: true,
    geometry: "cross",
  },
  ALLIUM: {
    id: 111,
    name: "Allium",
    texture: "allium.png",
    isTransparent: true,
    geometry: "cross",
  },
  AZURE_BLUET: {
    id: 112,
    name: "Azure Bluet",
    texture: "azure_bluet.png",
    isTransparent: true,
    geometry: "cross",
  },
  RED_TULIP: {
    id: 113,
    name: "Red Tulip",
    texture: "red_tulip.png",
    isTransparent: true,
    geometry: "cross",
  },
  ORANGE_TULIP: {
    id: 114,
    name: "Orange Tulip",
    texture: "orange_tulip.png",
    isTransparent: true,
    geometry: "cross",
  },
  WHITE_TULIP: {
    id: 115,
    name: "White Tulip",
    texture: "white_tulip.png",
    isTransparent: true,
    geometry: "cross",
  },
  PINK_TULIP: {
    id: 116,
    name: "Pink Tulip",
    texture: "pink_tulip.png",
    isTransparent: true,
    geometry: "cross",
  },
  OXEYE_DAISY: {
    id: 117,
    name: "Oxeye Daisy",
    texture: "oxeye_daisy.png",
    isTransparent: true,
    geometry: "cross",
  },
  CORNFLOWER: {
    id: 118,
    name: "Cornflower",
    texture: "cornflower.png",
    isTransparent: true,
    geometry: "cross",
  },
  LILY_OF_THE_VALLEY: {
    id: 119,
    name: "Lily of the Valley",
    texture: "lily_of_the_valley.png",
    isTransparent: true,
    geometry: "cross",
  },
  BROWN_MUSHROOM: {
    id: 120,
    name: "Brown Mushroom",
    texture: "brown_mushroom.png",
    isTransparent: true,
    geometry: "cross",
  },
  RED_MUSHROOM: {
    id: 121,
    name: "Red Mushroom",
    texture: "red_mushroom.png",
    isTransparent: true,
    geometry: "cross",
  },
  OAK_SAPLING: {
    id: 122,
    name: "Oak Sapling",
    texture: "oak_sapling.png",
    isTransparent: true,
    geometry: "cross",
  },
  SPRUCE_SAPLING: {
    id: 123,
    name: "Spruce Sapling",
    texture: "spruce_sapling.png",
    isTransparent: true,
    geometry: "cross",
  },
  BIRCH_SAPLING: {
    id: 124,
    name: "Birch Sapling",
    texture: "birch_sapling.png",
    isTransparent: true,
    geometry: "cross",
  },
  JUNGLE_SAPLING: {
    id: 125,
    name: "Jungle Sapling",
    texture: "jungle_sapling.png",
    isTransparent: true,
    geometry: "cross",
  },
  ACACIA_SAPLING: {
    id: 126,
    name: "Acacia Sapling",
    texture: "acacia_sapling.png",
    isTransparent: true,
    geometry: "cross",
  },
  DARK_OAK_SAPLING: {
    id: 127,
    name: "Dark Oak Sapling",
    texture: "dark_oak_sapling.png",
    isTransparent: true,
    geometry: "cross",
  },
  WATER: {
    id: 128,
    name: "Water",
    texture: "water_still.png",
    isTransparent: true,
    isFluid: true,
    geometry: "fluid",
  },
  OAK_SLAB: {
    id: 129,
    name: "Oak Slab",
    texture: "oak_planks.png",
    isTransparent: true,
    geometry: "slab",
  },
  SPRUCE_SLAB: {
    id: 130,
    name: "Spruce Slab",
    texture: "spruce_planks.png",
    isTransparent: true,
    geometry: "slab",
  },
  BIRCH_SLAB: {
    id: 131,
    name: "Birch Slab",
    texture: "birch_planks.png",
    isTransparent: true,
    geometry: "slab",
  },
  JUNGLE_SLAB: {
    id: 132,
    name: "Jungle Slab",
    texture: "jungle_planks.png",
    isTransparent: true,
    geometry: "slab",
  },
  ACACIA_SLAB: {
    id: 133,
    name: "Acacia Slab",
    texture: "acacia_planks.png",
    isTransparent: true,
    geometry: "slab",
  },
  DARK_OAK_SLAB: {
    id: 134,
    name: "Dark Oak Slab",
    texture: "dark_oak_planks.png",
    isTransparent: true,
    geometry: "slab",
  },
  COBBLESTONE_SLAB: {
    id: 135,
    name: "Cobblestone Slab",
    texture: "cobblestone.png",
    isTransparent: true,
    geometry: "slab",
  },
  STONE_BRICK_SLAB: {
    id: 136,
    name: "Stone Brick Slab",
    texture: "stone_bricks.png",
    isTransparent: true,
    geometry: "slab",
  },
  STONE_SLAB: {
    id: 137,
    name: "Stone Slab",
    texture: "stone.png", // Stone slab top usually implies smooth stone, but keeping simple
    isTransparent: true,
    geometry: "slab",
  },
};

// Helper to get block by ID
export const getBlockById = (id) => {
  return Object.values(BLOCKS).find((block) => block.id === id) || BLOCKS.AIR;
};
